GET http://localhost:3000/
###
GET http://localhost:3000/anime
###
GET http://localhost:3000/songs
###

GET http://localhost:3000/anime/6839b0da7b56326eed3cffe2
###
GET http://localhost:3000/songs/6839ac7b7b56326eed3cffd8
###
GET https://cse341-project2-u5by.onrender.com
###
GET https://cse341-project2-u5by.onrender.com/songs
###
GET https://cse341-project2-u5by.onrender.com/anime
###

// The following request will CREATE a new anime/songs in the database
POST http://localhost:3000/song HTTP/1.1
content-type: application/json

{
    "Title": "Si Boyd lang ang Love ko",
    "Artist": "Sheena Marie Ignacio",
    "Album": "Palagi",
    "Year": "2024"
}

### // The following request will UPDATE a song/anime in the database
PUT http://localhost:3000/users/6825f0f2ee3909e63153bce9 HTTP/1.1
content-type: application/json

{
    "firstName": "Cav",
    "lastName": "Gaylon",
    "email": "cav@gmail.com",
    "favoriteColor": "mink",
    "birthday": "1999-06-28"
}
### // The following request will DELETE a song/anime in the database
DELETE http://localhost:3000/songs/6840c6a664e4f468325fe849 HTTP/1.1
###
DELETE http://localhost:3000/anime/6839b02e7b56326eed3cffe0 HTTP/1.1
###
